/**
 * Comprehensive mapping of Airline IATA codes to their full names.
 * Updated: January 2026
 */
export const AIRLINE_NAMES: Record<string, string> = {
    'A3': 'Aegean Airlines',
    'AA': 'American Airlines',
    'AC': 'Air Canada',
    'AD': 'Azul Brazilian Airlines',
    'AE': 'Mandarin Airlines',
    'AF': 'Air France',
    'AH': 'Air Algérie',
    'AI': 'Air India',
    'AJ': 'Air Japan',
    'AK': 'AirAsia',
    'AM': 'Aeromexico',
    'AR': 'Aerolineas Argentinas',
    'AS': 'Alaska Airlines',
    'AT': 'Royal Air Maroc',
    'AV': 'Avianca',
    'AY': 'Finnair',
    'AZ': 'ITA Airways',
    'B2': 'Belavia',
    'BA': 'British Airways',
    'BE': 'Flybe',
    'BG': 'Biman Bangladesh Airlines',
    'BI': 'Royal Brunei Airlines',
    'BL': 'Jetstar Pacific',
    'BM': 'bmi',
    'BR': 'EVA Air',
    'BT': 'airBaltic',
    'BW': 'Caribbean Airlines',
    'BX': 'Air Busan',
    'CA': 'Air China',
    'CI': 'China Airlines',
    'CL': 'Lufthansa CityLine',
    'CM': 'Copa Airlines',
    'CX': 'Cathay Pacific',
    'CZ': 'China Southern Airlines',
    'D7': 'AirAsia X',
    'DD': 'Nok Air',
    'DE': 'Condor',
    'DG': 'Cebgo',
    'DL': 'Delta Air Lines',
    'DY': 'Norwegian Air Shuttle',
    'E5': 'Air Arabia Egypt',
    'ED': 'Air Explore',
    'EI': 'Aer Lingus',
    'EK': 'Emirates',
    'EN': 'Air Dolomiti',
    'ET': 'Ethiopian Airlines',
    'EW': 'Eurowings',
    'EY': 'Etihad Airways',
    'F9': 'Frontier Airlines',
    'FB': 'Bulgaria Air',
    'FD': 'Thai AirAsia',
    'FI': 'Icelandair',
    'FJ': 'Fiji Airways',
    'FM': 'Shanghai Airlines',
    'FR': 'Ryanair',
    'FZ': 'flydubai',
    'G3': 'GOL Linhas Aéreas',
    'G8': 'GoAir',
    'G9': 'Air Arabia',
    'GA': 'Garuda Indonesia',
    'GF': 'Gulf Air',
    'GK': 'Jetstar Japan',
    'H2': 'Sky Airline',
    'HA': 'Hawaiian Airlines',
    'HG': 'Niki',
    'HO': 'Juneyao Airlines',
    'HU': 'Hainan Airlines',
    'HX': 'Hong Kong Airlines',
    'HY': 'Uzbekistan Airways',
    'IB': 'Iberia',
    'ID': 'Batik Air',
    'IE': 'Solomon Airlines',
    'IG': 'Air Italy',
    'IR': 'Iran Air',
    'IX': 'Air India Express',
    'IZ': 'Arkia Israel Airlines',
    'J2': 'Azerbaijan Airlines',
    'J9': 'Jazeera Airways',
    'JD': 'Beijing Capital Airlines',
    'JJ': 'LATAM Brasil',
    'JL': 'Japan Airlines',
    'JP': 'Adria Airways',
    'JQ': 'Jetstar',
    'JU': 'Air Serbia',
    'K6': 'Cambodia Angkor Air',
    'KA': 'Dragonair',
    'KB': 'Drukair',
    'KC': 'Air Astana',
    'KE': 'Korean Air',
    'KF': 'Blue1',
    'KL': 'KLM Royal Dutch Airlines',
    'KM': 'Air Malta',
    'KQ': 'Kenya Airways',
    'KU': 'Kuwait Airways',
    'LA': 'LATAM Airlines',
    'LG': 'Luxair',
    'LH': 'Lufthansa',
    'LI': 'LIAT',
    'LJ': 'Jin Air',
    'LO': 'LOT Polish Airlines',
    'LP': 'LATAM Perú',
    'LR': 'Avianca Costa Rica',
    'LX': 'Swiss International Air Lines',
    'LY': 'El Al Israel Airlines',
    'MD': 'Air Madagascar',
    'ME': 'Middle East Airlines',
    'MF': 'XiamenAir',
    'MH': 'Malaysia Airlines',
    'MI': 'SilkAir',
    'MK': 'Air Mauritius',
    'MS': 'EgyptAir',
    'MU': 'China Eastern Airlines',
    'NH': 'All Nippon Airways',
    'NX': 'Air Macau',
    'NZ': 'Air New Zealand',
    'OA': 'Olympic Air',
    'OK': 'Czech Airlines',
    'OM': 'MIAT Mongolian Airlines',
    'OS': 'Austrian Airlines',
    'OU': 'Croatia Airlines',
    'OV': 'Estonian Air',
    'OZ': 'Asiana Airlines',
    'PC': 'Pegasus Airlines',
    'PG': 'Bangkok Airways',
    'PK': 'Pakistan International Airlines',
    'PR': 'Philippine Airlines',
    'PS': 'Ukraine International Airlines',
    'PX': 'Air Niugini',
    'PY': 'Surinam Airways',
    'QF': 'Qantas',
    'QH': 'Bamboo Airways',
    'QR': 'Qatar Airways',
    'QZ': 'Indonesia AirAsia',
    'RA': 'Nepal Airlines',
    'RB': 'Syrian Air',
    'RJ': 'Royal Jordanian',
    'S4': 'SATA International',
    'S7': 'S7 Airlines',
    'SA': 'South African Airways',
    'SB': 'Aircalin',
    'SC': 'Shandong Airlines',
    'SG': 'SpiceJet',
    'SK': 'SAS Scandinavian Airlines',
    'SL': 'Thai Lion Air',
    'SN': 'Brussels Airlines',
    'SQ': 'Singapore Airlines',
    'SS': 'Corsair International',
    'SU': 'Aeroflot',
    'SV': 'Saudia',
    'SW': 'Air Namibia',
    'T3': 'Eastern Airways',
    'TG': 'Thai Airways',
    'TK': 'Turkish Airlines',
    'TP': 'TAP Air Portugal',
    'TR': 'Scoot',
    'TU': 'Tunisair',
    'TW': "T'way Air",
    'U2': 'easyJet',
    'UA': 'United Airlines',
    'UK': 'Vistara',
    'UL': 'SriLankan Airlines',
    'UO': 'HK Express',
    'UX': 'Air Europa',
    'V7': 'Volotea',
    'VA': 'Virgin Australia',
    'VF': 'AJet',
    'VJ': 'VietJet Air',
    'VN': 'Vietnam Airlines',
    'VS': 'Virgin Atlantic',
    'VY': 'Vueling Airlines',
    'W6': 'Wizz Air',
    'WF': 'Widerøe',
    'WK': 'Edelweiss Air',
    'WY': 'Oman Air',
    'X3': 'TUI fly Deutschland',
    'XQ': 'SunExpress',
    'XY': 'Flynas',
    'YM': 'Montenegro Airlines',
    'Z2': 'Philippines AirAsia',
    'ZE': 'Eastar Jet',
    'ZH': 'Shenzhen Airlines',
    'ZI': 'Aigle Azur',
};

/**
 * Translates a carrier code to a full airline name.
 * @param carrierCode The IATA carrier code (e.g., 'LH')
 * @param fallbackName A fallback name if the code is not found in the local mapping
 * @returns The formatted airline name
 */
export function formatAirlineName(carrierCode: string, fallbackName?: string): string {
    if (!carrierCode) return fallbackName || 'Unbekannte Airline';

    // Use local translation if available
    if (AIRLINE_NAMES[carrierCode]) {
        return AIRLINE_NAMES[carrierCode];
    }

    // Fallback to provided name or the code itself
    return fallbackName || carrierCode;
}
